name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install pnpm using the standalone installer and force it to use bash
      - name: Install pnpm via standalone script
        run: |
          export SHELL=/bin/bash
          curl -fsSL https://get.pnpm.io/install.sh | bash -
          source ~/.bashrc

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          echo "PNPM_HOME is set to: $PNPM_HOME"
          echo "PATH is set to: $PATH"

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Build Frontend
        run: |
          cd fyndbox-frontend
          pnpm install
          pnpm run build

      - name: Build Backend
        run: |
          cd fyndbox-backend
          pnpm install
          pnpm run build
