name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm via standalone script
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | SHELL=bash sh -
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
        shell: bash

      - name: Install dependencies in root (for monorepo)
        run: pnpm install
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build Frontend
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          cd fyndbox-frontend
          pnpm install
          pnpm run build
        shell: bash

      - name: Build Backend
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          cd fyndbox-backend
          pnpm install
          pnpm run build
        shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying backend and frontend to the server"
          # Add your deployment script here
        shell: bash
