name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set the Shell (Explicit)
        run: |
          export SHELL=/bin/bash
          pnpm install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd fyndbox-frontend
          pnpm install # Install frontend-specific dependencies
          pnpm run build

      - name: Build Backend
        run: |
          cd fyndbox-backend
          pnpm install # Install backend-specific dependencies
          pnpm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying backend and frontend to the server"
