name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Install dependencies for both frontend and backend
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install

  # Backend tests
  # backend-test:
  # runs-on: ubuntu-latest
  # needs: install
  #steps:
  # - name: Run Backend Tests
  #   run: cd fyndbox-backend && pnpm run test

  # Frontend tests
  # frontend-test:
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - name: Run Frontend Tests
  #       run: cd fyndbox-frontend && pnpm run test

  # Build both frontend and backend
  # build:
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - name: Build Frontend
  #       run: |
  #         ls -al
  #         cd fyndbox-frontend
  #         ls -al
  #         pnpm run build

  #     - name: Build Backend
  #       run: |
  #         cd fyndbox-backend
  #         pnpm run build

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2

      - name: List Root Directory (Debugging)
        run: ls -al
        shell: bash

      - name: Check if Frontend Directory Exists
        run: test -d fyndbox-frontend || echo "Directory fyndbox-frontend not found!"
        shell: bash

      - name: Build Frontend
        run: |
          cd fyndbox-frontend
          ls -al
          pnpm run build
        shell: bash
      - name: Build Backend
        run: |
          cd fyndbox-backend
          pnpm run build
        shell: bash

  # Deploy to production (add your deployment commands here)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying backend and frontend to the server"
          # Add your deployment script or commands here
