name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install pnpm via standalone script
      - name: Install pnpm via standalone script
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | SHELL=bash sh -
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          echo "PNPM_HOME=$PNPM_HOME" >> $GITHUB_ENV
          echo "$PNPM_HOME/bin" >> $GITHUB_PATH

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies in root (for monorepo)
        run: pnpm install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          cd fyndbox-frontend
          pnpm install
          pnpm run build

      - name: Build Backend
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          cd fyndbox-backend
          pnpm install
          pnpm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying backend and frontend to the server"
