name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18.20.0
  PNMP_VERSION: 9.9.0

jobs:
  # Install dependencies and build both frontend and backend
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Install Node.js (v18)
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      # Step 3: Install PNPM
      - name: Install PNPM
        run: |
          npm install -g pnpm@${{env.PNMP_VERSION}}
          echo "PNPM version: $(pnpm --version)"

      # Step 4: Install dependencies in monorepo root
      - name: Install dependencies (root workspace)
        run: |
          pnpm install

      # Step 5: Build the frontend
      - name: Build Frontend (React + Vite)
        run: |
          cd fyndbox-frontend
          pnpm install
          pnpm run build
        working-directory: ./fyndbox-frontend

      # Step 6: Build the backend
      - name: Build Backend (NestJS)
        run: |
          cd fyndbox-backend
          pnpm install
          pnpm run build
        working-directory: ./fyndbox-backend

  # Deploy step to production
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying the application to the server"
          # Add your deployment script or commands here (e.g., rsync, FTP, SSH)
